# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
test:
  adapter: postgresql
  encoding: unicode
  database: concur_test
  pool: 1
  username: eugeneka
  password: 

mtest:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: concur_test
  pool: 1
  username: test
  password: test
  socket: /tmp/mysql.sock

development:
  adapter: postgresql
  encoding: unicode
  database: concur_development
  pool: 1
  username: eugeneka
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: concur_prroduction
  pool: 1
  username: eugeneka
  password:
